### ISSUE TITLE
Table cell width as defined by Polarion

### ISSUE THREAD

**Issue by yurtsevich-sbb** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#122]
### Discussed in https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **77dhe** June 20, 2024</sup>
We need for our documents more control over the table coloums width in the exported documents. At the moment the extension sets the width of each table cell to "auto" and left only the table cell hight at the value as defined by Polarion.
When I saw it right, this is processed in HtmlProcessor.java in adjustCellWidth(html).

What we need is, that the height of each table cell is set to "auto" and that the width value is left as defined by Polarion.

My proposal/request:

- Introduce an new Parameter "Keep table cell width" as boolean
- dependend on this parameter process the html in two ways:

1. As it is, when the parameter is not set
2. When the parameter is set: process the html and set the height of each table cell to "auto" instead of the width

Sorry, I am not able to make a code proposal for that.</div>

**Comment by grigoriev** [comment]
Partially fixed, waiting for https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/issues/91

**Comment by grigoriev** [comment]
We have introduced Webhooks for PDF-Exporter in v6.1.0.
HTML can be manipulated before sending it to WeasyPrint Service.

The examples of such Webhooks can be found [here](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter.webhook-samples)

**Comment by yurtsevich-sbb** [comment]
As an additional remark: in v6.1.0 of PDF-Exporter if you don't select option "Fit images and tables to page" exporter won't modify both width and height of table cells
