### ISSUE TITLE
No response when clicking Export to PDF button on LiveReport page

### ISSUE THREAD

**Issue by kschmiechen** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#142]
### Current Behavior

When trying to export a LiveReport Page, nothing happens but the logger logs:
2024-08-08 14:30:43,300 [ajp-nio-127.0.0.1-8889-exec-4 | u:appr] INFO  com.polarion.reina.web.internal.server.ria.ServerLogger - 2024-7-8 14:30:42.290  ERROR: Uncaught ReferenceError: PdfExporter is not defined 
line: 1 

### Expected Behavior

according to documentation, popup opens to configure pdf export

### Steps To Reproduce

1. Install PDF Exporter and WeasyPrint Service with below properties
2. set configuration property scriptInjection.mainHead=<script src="/polarion/pdf-exporter/js/starter.js"></script>
3. create live report page with content
4. add Export to PDF button widget
5. save the page
6. click the Export to PDF button

### Environment - OS

Windows

### Polarion version

2404

### Extension Version

5.7.2

### Anything else

<html><body>
<h3>Extension configuration properties</h3>

        
Configuration property | Value
-- | --
ch.sbb.polarion.extension.pdf-exporter.debug | true
ch.sbb.polarion.extension.pdf-exporter.internalizeExternalCss | false
ch.sbb.polarion.extension.pdf-exporter.weasyprint.connector | SERVICE
ch.sbb.polarion.extension.pdf-exporter.weasyprint.executable | weasyprint
ch.sbb.polarion.extension.pdf-exporter.weasyprint.pdf.variant | pdf/a-2b
ch.sbb.polarion.extension.pdf-exporter.weasyprint.service | http://localhost:9080

</body>
</html>

<html><body>
<h3>Extension configuration status</h3>

        
Configuration | Status | Info
-- | -- | --
Default Settings | OK |  
Document Properties Pane | OK |  
DLE Toolbar | WARNING | Not configured
LiveReport Button | OK |  
CORS (Cross-Origin Resource Sharing) | OK | CORS allowed origins: [http://localhost:8888]
WeasyPrint Python | OK | 3.12.4
WeasyPrint | OK | 62.3
WeasyPrint Service | OK | 62.4.0

</body>
</html>

**Comment by ukrishne** [comment]
Thanks I will try tomorrow

**Comment by grigoriev** [comment]
@kschmiechen fixed in v6.0.0

**Comment by kschmiechen** [comment]
thx, can confirm
