### ISSUE TITLE
LiveReportPage Export: Exporter does not account for URL Parameters

### ISSUE THREAD

**Issue by kschmiechen** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#147]
### Current Behavior

We have a LiveReport page which renders different content based on a URL parameter.
When I click the Export to PDF button, the page is exported as if it had not been opened with a URL Parameter.

### Expected Behavior

PDF is generated from the LiveReport page with the current URL Parameter.

### Steps To Reproduce

1. configure LiveReport page with different content based on URL Parameter
2. Open LiveReport page with URL Parameter
3. Create PDF using the Export to PDF button

### Environment - OS

Windows

### Polarion version

2404

### Extension Version

6.0.0

**Comment by grigoriev** [comment]
@kschmiechen could you please test v6.0.1 against your LiveReports?

**Comment by kschmiechen** [comment]
confirmed fixed
