### ISSUE TITLE
GET /api/convert/jobs in Swagger leads to connection refused error

### ISSUE THREAD

**Issue by schlami** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#191]
### Current Behavior

Using GET /api/convert/jobs in Swagger with latest release 6.2.0 leads to the following error message:
{
"0514b724-d307-4638-983f-c24994bf3312": {
"status": "FAILED",
"errorMessage": "javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused"
}
}

### Expected Behavior

see above

### Steps To Reproduce

see above

### Environment - OS

Linux

### Polarion version

2404

### Extension Version

6.2.0

**Comment by grigoriev** [comment]
Hi @schlami,

could you please provide us with server logs?

**Comment by grigoriev** [comment]
just to clarify: the returning response is not an error. It returns the list of jobs, and your job with id "0514b724-d307-4638-983f-c24994bf3312" has failed with error "javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused".

**Comment by grigoriev** [comment]
> I think you are right. The problem occured because the Weasyprint service crushed. Now I know where to look at. After restart it seems to work. I'm sorry for the confusion.

Could you please share the reason why WeasyPrint Service crushed?
It would be nice to have the issue with logs from weasyprint service [here](https://github.com/SchweizerischeBundesbahnen/weasyprint-service/issues). It would help us to make it more stable.
