### ISSUE TITLE
Images in Test Runs inaccessible

### ISSUE THREAD

**Issue by schlami** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#228]
### Current Behavior

With the version 7.1.1 all links and pictures in Test Runs become inaccessible (the sad icebear appears) if the Test Runs is exported by Polarion's built-in PDF exporter. If the extension is disabled, everything works fine.

Examples:
![image](https://github.com/user-attachments/assets/4bc10ae0-a72c-42b7-89b8-8cdfd46c3a1d)

![image](https://github.com/user-attachments/assets/106560f5-5057-4dc0-94e2-1a6a0402c912)

### Expected Behavior

see above

### Steps To Reproduce

see above

### Environment - OS

Linux

### Polarion version

2404

### Extension Version

7.1.1

**Comment by grigoriev** [comment]
@schlami,
thanks for reporting!
This should be fixed in v7.1.2, please hava a try.
