### ISSUE TITLE
PDF generation: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by HarryJulsing** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#235]
### Current Behavior

When exporting a livedoc, we get the following error message:

Error occurred during PDF generation: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused

### Expected Behavior

The pdf is not generated, but it should

### Steps To Reproduce

Click on export to pdf logo in livedoc
Then the popup Export to pdf appears
Click on export
Error appears in the popup
![image](https://github.com/user-attachments/assets/2d07d260-e80f-4d98-adcc-fdb574e10f88)

### Environment - OS

Linux

### Polarion version

2310

### Extension Version

7.1.2

**Comment by grigoriev** [comment]
Hi @HarryJulsing,

looks like there is not connection to weasyprint service. Please check weasyprint service status first.

Could you please provide us with screenshot of about page as well?

**Comment by HarryJulsing** [comment]
![image](https://github.com/user-attachments/assets/6377727b-efdf-476d-8304-a076229c85d8)

**Comment by HarryJulsing** [comment]
Hi Sergey,
The installation is at a server managed by Siemens, so we do not have direct access.
REST & Swagger have not been enabled, do we need to do that as well?
Thanks,
Harry

**Comment by grigoriev** [comment]
@HarryJulsing
could you please try with v7.2.0 ?

**Comment by HarryJulsing** [comment]
We updated to V 7.2.0 the issue still remains. Could it be a port issue?
