### ISSUE TITLE
Installation not working since 7.1.0 under Polarion 2310

### ISSUE THREAD

**Issue by LMTmwe** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#261]
### Current Behavior

As described in issue #238.
We do not get the the extension running with version 7.2.0, 7.1.2, 7.1.1, 7.1.0
Following error message occurs: HTTP Status 404 – Not Found and all icons are not found.
The WeasyPrint Service is running on a separate Linux server, but I guess this has no influence on this bug. With version 7.0.1, we run into issue  #222

### Expected Behavior

To work as described in the documentation

### Steps To Reproduce

1.     Install the plugin as described in the documentation with deleting the .config folder
2.     restart Polarion
3.     go to the project
4.     enter Administration and open the "PDF Export -> About" page

### Environment - OS

Windows

### Polarion version

2310

### Extension Version

7.2.0, 7.1.2, 7.1.1, 7.1.0

**Comment by ralfsmolarek3** [comment]
Unfortunately we have to confirm. Investigation in progress
