### ISSUE TITLE
Bulk PDF Export as zip-File

### ISSUE THREAD

**Issue by Alex-SBB** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#290]
### Description

The widget "Bulk PDF Export" shall offer the option to export single files into a zip-file.

### Motivation

Easier recognition and better handling of the downloaded files

### Proposed Solution (optional)

A checkbox in the configuration or widget-configuration with to options: 
- export as zip-file 
- export as separate files directly into download folder (as implemented now)

**Comment by ralfsmolarek3** [comment]
Hello Alex,
creating a zip file would require to have all the data in memory or additional access to the filesystem. At this point we will avoid both - until someone comes along with a great solution. 
Current workaround: reconfigure your browser to point the download folder to a new location. After batch-export - zip that folder
