### ISSUE TITLE
Customizable Watermarks

### ISSUE THREAD

**Issue by LMTmwe** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#292]
### Description

 Some use cases make it necessary to customize the watermark string.

### Motivation

In our case we want to mark documents as invalid or as a draft.

### Proposed Solution (optional)

A customizable configuration String field is preferred. Otherwise an enum field with more options including "DRAFT" and "INVALID" would be sufficient.

**Comment by ralfsmolarek3** [comment]
This is already possible using pngs but I guess you like to define just a text and have it overlayed (left/right, top/bottom, ....)?

**Comment by LMTmwe** [comment]
Thanks for this information. Then this request can be closed. Sorry, I did not know this.
