### ISSUE TITLE
Export of other language

### ISSUE THREAD

**Issue by 77dhe** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#58]
### Current Behavior

If I switch the language of a document and export the pdf, always the basic language will be exported

### Expected Behavior

If I switch the language of a document and export the pdf, the choosen and displayed language shall be exported

### Steps To Reproduce

Choose a document with two ore more languages and swith the language to an other language, than the basic one.
![Switch language](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/assets/170075852/d836454f-8ed6-4d87-9067-5aa204a41f87)

Export the pdf.

### Environment - OS

Linux

### Polarion version

2310

### Extension Version

3.12.0

**Comment by grigoriev** [comment]
This is a missing functionality of PDF-Exporter: there were no such requirements. 
Will be implemented soon.
