### ISSUE TITLE
Warning message when exporting the current, non-final version of a live document

### ISSUE THREAD

**Issue by ukrishne** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#64]
### Description

Show a warning message when exporting the current, non-final version of a live document.

### Motivation

This warning helps users understand that the document is still being edited. Exporting it now might result in inconsistencies if the document changes later.

### Proposed Solution (optional)

![image](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/assets/45649812/05741eb8-2d33-469c-9b74-5ecb773ef2b7)

**Comment by grigoriev** [comment]
@ralfsmolarek3 what do you thing about such functionality?

**Comment by ralfsmolarek3** [comment]
@ukrishne thanks a lot for the enhancement request!

I believe such warnings should be done on an organizational level. In many cases this could annoy people more than it help. As a workaround the PDF-export could be triggered through a script which does those checks/warnings.

However this feature could be part of a more generic enhancement we have already thought about: **making the style-packages depending on logic**

Inside the administration we define certain dependencies e.g.:

- Status, type of LiveDoc (minimal functionality for the first implementation)
- Any custom field of the LiveDoc
- Name, space, project (as the configuration can be defined on a global level) of LiveDoc using regex
- Role(s) of the user

If all dependencies are fulfilled a style-package will be used: **so every dependency-set is one style-package assinged**. The configurations are similar defined like the custom-sets in Polarion (having an order and are checked in that order. First "hit" will be used). One configuration has to be defined as the fallback (will be used if no other will match).

What do you think?

**Comment by ukrishne** [comment]
@ralfsmolarek3 : many thanks Ralf for your detailed comment.  agreed, workaround you have suggested can be done at organisation level but as you are already considering as part of generic enhancements i am ok with it. could be a small note can be added about non baselined version export.

**Comment by ralfsmolarek3** [comment]
@ukrishne not sure about the "non baselined version" as we always export a specific revision (even if it is head). So the only point is if someone hasn't created a baseline in advance. However this can be done any time later.
You know the variable we have for header/footer?!

> ![image](https://github.com/user-attachments/assets/aac03358-97e2-453d-a7b6-80f00faeac5f)

**Comment by ukrishne** [comment]
Hi Ralf, thanks for your reply. We would need to give info that user is
exporting current version which is live and can undergo modification and
pdf become out of sync. This info has to given only during current version
export. Not applicable for baselines.

**Comment by kschmiechen** [comment]
I think rendering a warning in the exported PDF could already be done using Velocity scripts in the cover sheet and header footer definition.
Based on the document status or whether there is a baseline for the current revision, you can include a warning that this is a not baselined version.

**Comment by ukrishne** [comment]
@kschmiechen : thanks for your comment. Yes agreed, but my request was not show the warning in the exported pdf but just to show information to user that you are trying to export current version.
