### ISSUE TITLE
Attribute Coloring for Enhanced Tagging and Visibility in PDF Exports from Polarion Live Document

### ISSUE THREAD

**Issue by ukrishne** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#83]
### Description

Introduce a feature that allows users to assign colors to specific attributes within Polarion Live Documents. When exporting these documents as PDFs, the color-coded attributes will be clearly displayed, enhancing the readability and visual categorization of critical information.

### Motivation

This feature aims to improve the usability of exported PDFs by providing a visual distinction for important attributes. Color-coding attributes based on their relevance or significance, such as "Safety Related," "RAM Related," and "Security Related," can help users quickly identify and focus on key information. This enhancement is particularly valuable in complex documents where quick recognition of critical attributes can significantly aid in decision-making and overall efficiency.
Benefits:
Enhanced Visibility in PDFs: Color-coding makes it easier for users to quickly identify important attributes in exported PDFs.
Improved Categorization: Different colors help categorize attributes by their relevance or type, aiding in better organization and readability in the PDF format.
User Customization: Provides flexibility for users to tailor their document appearance according to their preferences and needs in the exported PDFs.
Increased Efficiency: Reduces the time needed to locate and assess critical attributes in PDFs, enhancing overall productivity and decision-making.

### Proposed Solution (optional)

![image](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/assets/45649812/6fa4a8d4-dadb-412d-9354-212a47e0efe5)

**Comment by grigoriev** [comment]
@ralfsmolarek3 could you please check the proposed feature request?

**Comment by ralfsmolarek3** [comment]
@ukrishne not sure whether I understand the request. Are you looking for a definition of certain "phrases" (word, sentences) which should be reformatted in the whole LiveDoc?

**Comment by ukrishne** [comment]
Hi Ralf, i am trying to explain that if i would like to know if the requirement is safety relevent or not quickly i cant check it in the whole pdf file. instead i have custom attribute safety relevent is set to yes/no then if you allow us to make safety tagging (please check the screenshot) if safety relevent is set to "yes". so that i can undeerstand quickly.

**Comment by ralfsmolarek3** [comment]
@ukrishne so if I understand your need, you like to print the custom attribute at the end of (e.g.) title (like in your screenshot)!? You might have it already in a table view but this you would define as not user-friendly enough?

**Comment by ukrishne** [comment]
HI Ralf, thanks again for your comment.
I  dont add the attribute safety relevent = yes/no in to table in each workitem , i just need to mark in red or as shown in my screenshot(superscript)  if safety relevent = yes.

In general, if you are already working on colouring particular attribute data during configuration for export then still we can manage with such option.

Best Regards
Umesha Krishnegowda

**Comment by grigoriev** [comment]
Hi @ukrishne,

we have introduced Webhooks for PDF-Exporter in v6.1.0.
HTML can be manipulated before sending it to WeasyPrint Service.

The examples of such Webhooks can be found [here](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter.webhook-samples)

So you can implement the Webhook for adding required coloring.
