### ISSUE TITLE
plugin documentation: link doesnt work.

### ISSUE THREAD

**Issue by grigoriev** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#97]
### Discussed in https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **ukrishne** July 12, 2024</sup>
Dear Team,

plugin documentation is taking us to SBB portal where public is not having permission. can you please make it available for public.
![image](https://github.com/user-attachments/assets/2de9cc73-6c5c-4824-8c16-7166a912feec)

thanks in Advance</div>

**Comment by ukrishne** [comment]
perfect. great support and work
